### ISSUE TITLE
Initial 'npm serve' produces worrying 'fix' output

### ISSUE THREAD

**Issue by leegee** [gothinkster/vue-realworld-example-app#111]
```
$ npm run serve

> realworld-vue@0.1.0 serve c:\Users\leege\src\vue-realworld-example-app
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin
 WARNING  Compiled with 7 warnings                   11:00:15 AM
Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\components\Comment.vue:18:69:
  16 |       <span class="date-posted">{{ comment.createdAt | date }}</span>
  17 |       <span v-if="isCurrentUser" class="mod-options">
> 18 |         <i class="ion-trash-a" v-on:click="destroy(slug,
comment.id);"></i>
     |
           ^
  19 |       </span>
  20 |     </div>
  21 |   </div>


1 warning found.
1 warning potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\components\CommentEditor.vue:6:51:
  4 |     <form
  5 |       class="card comment-form"
> 6 |       v-on:submit.prevent="onSubmit(slug, comment);"
    |                                                   ^
  7 |     >
  8 |       <div class="card-block">
  9 |         <textarea


1 warning found.
1 warning potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\components\VPagination.vue:9:41:
   7 |         :key="page"
   8 |         :class="paginationClass(page)"
>  9 |         @click.prevent="changePage(page);"
     |                                         ^
  10 |       >
  11 |         <a class="page-link" href v-text="page" />
  12 |       </li>


1 warning found.
1 warning potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\views\ArticleEdit.vue:7:61:
   5 |         <div class="col-md-10 offset-md-1 col-xs-12">
   6 |           <RwvListErrors :errors="errors" />
>  7 |           <form v-on:submit.prevent="onPublish(article.slug);">
     |
   ^
   8 |             <fieldset :disabled="inProgress">
   9 |               <fieldset class="form-group">
  10 |                 <input


warning: Delete `;` (prettier/prettier) at src\views\ArticleEdit.vue:40:64:
  38 |                   placeholder="Enter tags"
  39 |                   v-model="tagInput"
> 40 |                   v-on:keypress.enter.prevent="addTag(tagInput);"
     |
      ^
  41 |                 />
  42 |                 <div class="tag-list">
  43 |                   <span


warning: Replace `;">⏎···················` with `">` (prettier/prettier) at src\views\ArticleEdit.vue:48:74:
  46 |                     :key="tag + index"
  47 |                   >
> 48 |                     <i class="ion-close-round" v-on:click="removeTag(tag);">
     |
                ^
  49 |                     </i>
  50 |                     {{ tag }}
  51 |                   </span>


3 warnings found.
3 warnings potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\views\Login.vue:15:63:
  13 |             <li v-for="(v, k) in errors" :key="k">{{ k }} {{ v | error }}</li>
  14 |           </ul>
> 15 |           <form v-on:submit.prevent="onSubmit(email, password);">
     |
     ^
  16 |             <fieldset class="form-group">
  17 |               <input
  18 |                 class="form-control form-control-lg"


1 warning found.
1 warning potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\views\Profile.vue:22:43:
  20 |                 class="btn btn-sm btn-secondary action-btn"
  21 |                 v-if="profile.following"
> 22 |                 @click.prevent="unfollow();"
     |                                           ^
  23 |               >
  24 |                 <i class="ion-plus-round"></i> &nbsp;Unfollow
  25 |                 {{ profile.username }}


warning: Delete `;` (prettier/prettier) at src\views\Profile.vue:30:41:
  28 |                 class="btn btn-sm btn-outline-secondary action-btn"
  29 |                 v-if="!profile.following"
> 30 |                 @click.prevent="follow();"
     |                                         ^
  31 |               >
  32 |                 <i class="ion-plus-round"></i> &nbsp;Follow
  33 |                 {{ profile.username }}


2 warnings found.
2 warnings potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `;` (prettier/prettier) at src\views\Settings.vue:7:50:
   5 |         <div class="col-md-6 offset-md-3 col-xs-12">
   6 |           <h1 class="text-xs-center">Your Settings</h1>
>  7 |           <form @submit.prevent="updateSettings();">
     |                                                  ^
   8 |             <fieldset>
   9 |               <fieldset class="form-group">
  10 |                 <input


1 warning found.
1 warning potentially fixable with the `--fix` option.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore
  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.45:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.


```

**Comment by klamping** [comment]
All these errors are just 'prettier' settings that don't like having a semi-colon in some of the inline JS. Absolutely nothing to really worry about here; you can just ignore it (or submit a PR with the `;`'s removed)
